"""empty message

Revision ID: 33eb26ca2a71
Revises: 5ff40f141cbf
Create Date: 2024-07-19 19:18:39.406525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33eb26ca2a71'
down_revision: Union[str, None] = '5ff40f141cbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_log',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name='search_log_location_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], name='search_log_user_id_fkey')
    )
    # ### end Alembic commands ###
