"""empty message

Revision ID: 596db65b0254
Revises: 33eb26ca2a71
Create Date: 2024-07-19 19:21:30.132895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '596db65b0254'
down_revision: Union[str, None] = '33eb26ca2a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_history', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_history', 'created_at')
    # ### end Alembic commands ###
