"""empty message

Revision ID: 5ff40f141cbf
Revises: 820f52814c96
Create Date: 2024-07-19 19:12:59.671876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ff40f141cbf'
down_revision: Union[str, None] = '820f52814c96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_history', sa.Column('location_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_history', 'location_id')
    # ### end Alembic commands ###
